apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.configmap" . }}
  namespace: {{ include "common.required.namespace" . }}
data:
{{- if .Values.configmap.enabled -}}
{{- include "common.configmap.data" . | nindent 2 -}}
{{- end }}
{{- if .Values.ConfigmapAdvancedConfiguration.enabled }}
  {{ .Values.ConfigmapAdvancedConfiguration.volumeItems.key }}: |-
{{- include "common.tplvalues.render" (dict "value" .Values.ConfigmapAdvancedConfiguration.configmapData "context" $) | nindent 4 }}
{{- end }}