apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.secret" . }}
  namespace: {{ include "common.required.namespace" . }}
type: Opaque
data:
{{- if .Values.secret.enabled -}}
{{- include "common.secrets.data" . | nindent 2 -}}
{{- end }}
{{- if .Values.SecretAdvancedConfiguration.enabled }}
  {{ .Values.SecretAdvancedConfiguration.volumeItems.key }}: |-
{{- include "common.tplvalues.render" (dict "value" .Values.SecretAdvancedConfiguration.secretData "context" $) | nindent 4 }}
{{- end }}
