{{- if or (eq "false" (include "common.progressiveDelivery.enabled" .)) (not (eq "true" (include "common.progressiveDelivery.checkReleaseType" .))) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.service" . }}
  namespace: {{ include "common.required.namespace" . }}
  labels:
    app: {{ .Chart.Name }}
  annotations: {{ include "common.service.annotations" . }}
spec:
  ports:
    - name: {{ include "common.service.portName" . }}
      {{- include "common.service.nodePort" . | nindent 6 }}
      port: {{ include "common.service.port" . }}
      targetPort: {{ include "common.service.targetPort" . }}

  selector: {{- include "common.labels.baseSelectors" . | nindent 4 }}
  type: {{ include "common.service.type" . }}
  {{ include "common.service.loadBalancerIP" . }}
{{- end -}}
