// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.cloud.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

/* MSAL properties
   These proerties are read from the environment variables created in the Helm charts.
   For local development, the properties are created in /assets/env.js
*/

export const environment = {
  production: false,
  version: '1.2.0',
  msalApplicationId: '3a4e0b0b-2db6-4ade-86ed-e18a3eb132d8',
  msalRedirectUri: 'http://localhost:4200',
  msalAuthority: 'https://login.microsoftonline.com/fc341639-d0f7-4b9d-9415-164ac3a012a5',
  msalGraphURL: 'https://graph.microsoft.com/v1.0/me',
  apiBackendUrl: '/dev-api',
};
